title: Sylvester Kaczmarek
url: https://sylvesterkaczmarek.github.io
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache

masthead_title: ""
logo: /assets/images/sylvester-kaczmarek.jpeg

author:
  name: Sylvester Kaczmarek
  avatar: /assets/images/sylvester-kaczmarek.jpeg
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/sylvesterkaczmarek/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sylvesterkaczmarek"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sylvesterkaczmarek.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:space.stranger698@8shield.net"
