title: Prof. Sylvester Kaczmarek
url: https://sylvesterkaczmarek.github.io
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache

masthead_title: "Space AI & Security"   # small strapline in the top bar

author:
  name: Prof. Sylvester Kaczmarek
  avatar: /assets/images/sylvester-kaczmarek.jpeg
  bio: Secure autonomy for space systems.
  location: London, UK
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/sylvesterkaczmarek/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sylvesterkaczmarek"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sylvesterkaczmarek.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:assistant@sylvesterkaczmarek.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-0393-228X"
